config/routes.rb
Rails.application.routes.draw do
 
  root 'dashboard#home'

 resources :users, only: [:index, :show]
 resources :videos, only: [:index, :show]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :users_videos
  has_many :videos, through: :users_videos
  # How does a user relate to a video?
  # You should be able to run the following:
  #    User.last.videos
end

app/models/users_video.rb
class UsersVideo < ActiveRecord::Base
	belongs_to :user
    belongs_to :video  
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :users_videos
  has_many :users, through: :users_videos 
  # How does a video relate to a user?
  # You should be able to run the following:
  #    Video.last.users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def home
  	@videos = Video.all
    @histogram = LazyHighCharts::HighChart.new('column') do |f|
      @videos.each do |v|
        f.series(:name=>v.title, :data => [v.users.count])
      end
      f.title({ :text=>"Video View Stats"})
      f.legend({:enabled => false})
      f.tooltip({:formatter => 'function(){return this.series.name + ": " + this.y}'.js_code})
      f.options[:chart][:defaultSeriesType] = "column"
      f.options[:xAxis] = {:labels => {:enabled => false}}
      f.options[:yAxis][:title] = {:text=>"Views"}
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.paginate(:page => params[:page], :per_page => 25)
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
  	@videos = Video.all
  end

  def show
  	@video = Video.find(params[:id])
  	@users = @video.users.paginate(:page => params[:page], :per_page => 25)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/dashboard/home.html.erb
<% provide(:title, "Dashboard") %>
<h1 class="page-header">Historgram</h1>

<%= high_chart("bar_chart", @histogram) %>

<table class="table">
  <tr>
    <th>Video Title</th>
    <th>Users watched</th>
  </tr>
  <% @videos.each do |v| %>
  <tr>
    <td><%= link_to v.title, v =%></td>
    <td><%= v.users.count =%></td>
  </tr>
  <% end %>
</table>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <p class="navbar-text"><%= link_to "FULLSCREEN", root_path %></p>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Videos", videos_path %></li>
      </ul>
    </nav>
  </div>
</header

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | FullscreenInterview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/users/_user.html.erb
<li class="list-group-item">
  <%= link_to user.name, user %>
</li>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h1 class="page-header">All users</h1>

<%= will_paginate @users, renderer: BootstrapPagination::Rails %>
<ul class="list-group user-list">
  <%= render @users %>  
</ul>
<%= will_paginate @users, renderer: BootstrapPagination::Rails %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1 class="page-header"><%= @user.name %></h1>

<ul class="list-group video-list">
  <h3>Watched videos</h3>
  <%= render @user.videos %>
</ul>

app/views/videos/_video.html.erb
<li class="list-group-item">
  <%= link_to video.title, video %>
</li>

app/views/videos/index.html.erb
<% provide(:title, "All Videos") %>
<h1 class="page-header">All videos</h1>

<ul class="list-group video-list">
  <%= render @videos %>  
</ul>

app/views/videos/show.html.erb
<% provide(:title, @video.title) %>
<h1 class="page-header"><%= @video.title %></h1>

<%= will_paginate @users, renderer: BootstrapPagination::Rails %>
<ul class="list-group user-list">
  <h3>Watched by</h3>
  <%= render @users %>
</ul>
<%= will_paginate @users, renderer: BootstrapPagination::Rails %>